### ISSUE TITLE
[Feature Request] Move "test" sketches into "examples" folder

### ISSUE THREAD

**Issue by aentinger** [arduino-libraries/Arduino_UnifiedStorage#15]
Normally we store only host-executed unit tests within the `extra/tests` sub-folder.

Moving those sketches over in the `examples` folders has the added benefit of finding them quickly via the IDE.

**Comment by aliphys** [comment]
The rational for having the tests in the `extras/tests` subfolder was mentioned as part of https://github.com/arduino/arduino-lint/issues/588 . Specifically:
> Including test sketches, which have no/little pedagogical value, will increase the complexity of the user experience. Advanced users can always see the test sketches in the repository or local installation of the library.

**Comment by sebromero** [comment]
These tests are more like functional tests, so, yes maybe they should be in a different place. I agree though, that I don't want the end users to see them as they are not meant to be executed by them. We have separate sketches to demonstrate the features of this library. What if we create a new folder `functional-tests`? Would that make it clearer?

**Comment by aliphys** [comment]
@sebromero If we create a new folder called `functional-tests`, it would need to be inside the `extras` folder: `extras/functional-tests`. 

[Rule LD003](https://arduino.github.io/arduino-lint/1.2/rules/library/#stray-sketch-ld003) of the linter does not allow for any `.ino` sketches to be outside the `examples` or `extras` (sub)folders.
> A sketch was found outside the library's `examples` and/or `extras` subfolders. Example sketches must be placed in the standardized location.

https://github.com/arduino/arduino-lint/blob/9e5ae478fffcb39f42d8dce7911912891e12b5ad/internal/rule/ruleconfiguration/ruleconfiguration.go#L1303-L1319

**Comment by sebromero** [comment]
@aliphys Sure that's what I meant.
