### ISSUE TITLE
Arduino_UnifiedStorage causing my Arduino to crash

### ISSUE THREAD

**Issue by Ken-488** [arduino-libraries/Arduino_UnifiedStorage#21]
I am new to GitHub and relatively new to Arduino programming, so apologies if this is my fault.

Including the `Arduino_UnifiedStorage.h` header file in my sketch causes the the arduino to crash after its first serial print command.

I am using a Portenta Machine Control board that has a Portenta H7 processor board.

It was previously working and then i started a new sketch and include the file. That was when my problems started, now none of my older sketches work, or the examples included in the library. this was the first time that the `#include` was in `<Arrows>` rather than `"Quotationmarks"`.

---

I have tried removing the library and re installing it.

**Comment by aliphys** [comment]
Hello @Ken-488 ,
Thanks for providing feedback! Can you provide the sketch you used? cc @cristidragomir97

**Comment by sebromero** [comment]
Hi @Ken-488 If I understand correctly it prints `Reading data from files using seek and available:` and then crashes which makes the red LED blink the SOS pattern. Correct?

**Comment by Ken-488** [comment]
hi, yes that is exactly what it is doing, just never see the red light as it is inside the Portenta Machine Control. i have just tried a section of memory sticks and reformatted them. it still has the same result but it does write the 3 folders and files to the sticks before crashing.

**Comment by sebromero** [comment]
@Ken-488 Odd. Can you please check if you have the latest version (0.2.0) of [Arduino_USBHostMbed5](https://github.com/arduino-libraries/Arduino_USBHostMbed5/releases) installed?
Can you also add some print statements after the `changeMode` calls to see if it reaches that part of the code?
If necessary, please add some additional print statements further down in the code so we can pinpoint the function that makes the board crash.

**Comment by Ken-488** [comment]
Hi, yes i have version 0.2.0. Just tried that, it crashed after printing the first Serial.print() or Serial.println() (Tried both) command inserted as below

Serial.begin(115200);
  while (!Serial);
 
 Serial.print("Start setup");
 Serial.print("Start setup2");


  if(!unifiedStorage.begin(FS_FAT)){
    Serial.println("Error mounting storage device.");
  }

**Comment by sebromero** [comment]
@cristidragomir97 Any idea on how to debug this?

**Comment by Ken-488** [comment]
Hi, are you able to recreate the problem?  i previously spent a few days tying  to isolate the problem prior to posting. the library was used in a different program, one day it was working then i added another library and changed the sketch, then i had some problem compiling the modified sketch (unable to find Libraries). so i deleted all the  #include statements at the start of the sketch, i re included all of the libraries using the include library option in the menu. the changed the statement from 

#include "Arduino_UnifiedStorage.h" 
to 
#include <Arduino_UnifiedStorage.h>

after much more fighting to get the sketch to complie and find all the liaries, then it would compile and crash and spent a long time trying to isolate why it crashed, i could never get the Library to function with any sketch, always the same problem. during this time i got to the concussion that it probably was a conflict between "Arduino_UnifiedStorage.h" library and the Serial.print() Command, i did wonder if it was a problem from an update or with the Arduino IDE, so did try re installing it, i've not tried another computer yet.

**Comment by sebromero** [comment]
@Ken-488 No, we haven't. We did extensive testing with this library, also with Portenta Machine Control, but we haven't encountered the issue that you're describing.

**Comment by Ken-488** [comment]
oh, that is sounding a lot like my computer is causing the problem when it is compiling then

**Comment by sebromero** [comment]
It's possible. We could create a binary from your sketch and share that with you so you can test if your computer creates a faulty binary or if the issue is elsewhere.

**Comment by Ken-488** [comment]
I have  Bin File here, not sure how to post it, (sorry new to this)

**Comment by sebromero** [comment]
@Ken-488 You probably need to create a zip file and then attach it here along with a comment. See https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Comment by Ken-488** [comment]
[sketch_oct19a.zip](https://github.com/arduino-libraries/Arduino_UnifiedStorage/files/13044755/sketch_oct19a.zip)

i have zipped up the whole sketch folder

**Comment by alrvid** [comment]
Thank you for reporting the problem! I've been able to reproduce it when running your binary, but the crash doesn't happen if I compile the same sketch on my own computer. I'll have a closer look at it and see if I can figure out why it happens.

**Comment by Ken-488** [comment]
Thank you for the update, this could be quite challenging to figure out, i have already tried uninstalling Arduino IDE, deleting any remaining files and then reinstalling it.

**Comment by alrvid** [comment]
It seems like the bug you've run into is in fact the same bug that's reported here for the Giga:

https://github.com/arduino-libraries/Arduino_USBHostMbed5/issues/29

We're still actively working on it.

**Comment by sebromero** [comment]
Hi @Ken-488 ! Could you try again with the latest release of this library and also [this](https://github.com/arduino-libraries/Arduino_USBHostMbed5/releases/tag/0.3.1) release of Arduino_USBHostMbed5?

**Comment by Ken-488** [comment]
Hi, i can confirm that Arduino_USBHostMbed5 0.3.1 appears to have resolved the issue i was experiencing, Thank you all for you help,
