### ISSUE TITLE
File size

### ISSUE THREAD

**Issue by Goliath86** [arduino-libraries/Arduino_UnifiedStorage#50]
Hi,
only one question: how is it possible to get the size of a file without reading all of it? Is it at least possible?

Thanks in advance

Mattia

**Comment by per1234** [comment]
Hi @Goliath86. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
